package com.alerts.AlertTypes;

import java.util.ArrayList;

import com.alerts.Alert;
import com.data_management.PatientRecord;

/**
 * Manual Alert creator emmitted by HealthDataGenerator
 * 
 * @author Yan
 */
public class TriggeredButtonAlert implements AlertCondition {

    /**
     * Returns manual alert generated by nurses
     * @param patientId String value of Id of a patient
     * @param records ArrayList of records of a patient to check
     * @return Manual Alert
     */
    @Override
    public Alert evaluate(String patientId, ArrayList<PatientRecord> records) {
        return new Alert(
            patientId, 
            "Manual Alert", 
            System.currentTimeMillis());
    }
    
}
