package com.alerts.AlertStrategies;

import java.util.ArrayList;

import com.alerts.AlertTypes.Alert;
import com.alerts.AlertTypes.TriggeredButtonAlert;
import com.data_management.PatientRecord;

/**
 * Strategy for manual alert
 * 
 * @author Yan
 */
public class TriggeredButtonStrategy implements AlertStrategy {

        /**
     * Returns manual alert generated by nurses
     * @param records ArrayList of records of a patient
     * @return Manual Alert
     */
    @Override
    public Alert checkCondition(ArrayList<PatientRecord> records) {
        if (records.size() == 0) {
            return new TriggeredButtonAlert(
                "-1", 
                "Manual Alert", 
                System.currentTimeMillis());
        }
        return new TriggeredButtonAlert(
                String.valueOf(records.get(0).getPatientId()), 
                "Manual Alert", 
                System.currentTimeMillis());
    }
    
}
